name: ADB-CD

on: 
  push:
    branches: [ main ]
  
  workflow_dispatch:

jobs:
  deploy-to-DEV:
   name: Deploy to Dev
   uses: .github/workflows/deployment.yml@main

  deploy-to-PROD:
   name: Deploy to Prod
   uses: .github/workflows/deployment.yml@main
    
