name: Notebook-Deployment-Databricks
on:
  workflow_call:
   inputs:
      target_Environment:
        description: Environment to Deploy
        type: string
        required: true

jobs:
  push_to_db:
    name: Deploying to ${{ inputs.target_Environment }}
    runs-on: ubuntu-latest
    environment:
     name: ${{ inputs.target_Environment }}
      
    steps:
      - name: Checkout current repository
        uses: actions/checkout@v4
      
      - name: Azure Login
        uses: Azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Databricks CLI config
        run: |
            pip install databricks-cli 
            dbToken=$(az account get-access-token --resource 2ff814a6-3304-4ab8-85cb-cd0e6f879c1d --query "accessToken" --output tsv)
            echo "DB Token is $dbToken"
            echo "DATABRICKS_TOKEN=$dbToken" >> $GITHUB_ENV
            cat > ~/.databrickscfg << EOF 
            [DEFAULT] 
            host = ${{ secrets.DATABRICKS_HOST_URL }} 
            token = ${{ env.DATABRICKS_TOKEN }}
            jobs-api-version = 2.1 
            EOF
            databricks workspace import_dir ${{ github.workspace }}/Notebooks ${{ vars.WORKSPACE_FOLDER }} --exclude-hidden-files --overwrite
    
      - name: Deploy code to databricks workspace
        uses: microsoft/databricks-import-notebook@v1.0.0
        with:
          # Databricks host
          databricks-host: ${{ secrets.DATABRICKS_HOST_URL }}
          # LOCAL_NOTEBOOKS_PATH
          local-path: ${{ github.workspace }}/Notebooks
          # REMOTE_NOTEBOOK_PATH
          remote-path: ${{ vars.WORKSPACE_FOLDER }}
