name: Notebook-Deployment-Databricks
on:
  workflow_call:
   inputs:
      target_Environment:
        description: Environment to Deploy
        type: string
        required: true

jobs:
  push_to_db:
    name: Deploying to ${{ inputs.target_Environment }}
    runs-on: ubuntu-latest
    environment:
     name: ${{ inputs.target_Environment }}
      
    steps:
      - name: Checkout current repository
        uses: actions/checkout@v4
      
      - name: Azure Login
        uses: Azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: install-databricks-cli
        uses: microsoft/install-databricks-cli@v1.0.0
        env:
         DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST_URL }}
         DATABRICKS_CLIENT_ID: ${{ secrets.SP_NAME }}
         DATABRICKS_CLIENT_SECRET: ${{ secrets.ADB_SP_TOKEN }}

      - name: Deploy code to databricks workspace
        uses: microsoft/databricks-import-notebook@v1.0.0
        with:
          # Databricks host
          databricks-host: ${{ secrets.DATABRICKS_HOST_URL }}
          databricks-token: ${{ secrets.ADB_SP_TOKEN }}
          # LOCAL_NOTEBOOKS_PATH
          local-path: ${{ github.workspace }}/Notebooks/R2R
          # REMOTE_NOTEBOOK_PATH
          remote-path: ${{ vars.WORKSPACE_FOLDER }}
